name: Label PRs

on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      pull-requests: write
      contents: read
    uses: GregTech-Engineering/GithubActions/.github/workflows/labeler.yml@main
    secrets: inherit