name: Publish on Release

on:
  release:
    types: [released]

jobs:
  meta:
    name: Metadata
    runs-on: ubuntu-latest
    outputs:
      CHANGELOG: ${{ steps.changelog.outputs.changelog }}
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Get Config
        uses: actions/checkout@v4
        with:
          ref: 'main'
          sparse-checkout: '.github/json'
      - name: Generate changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: './.github/json/config.json'
          ignorePreReleases: true
          fetchViaCommits: true
          failOnError: true

  publish-20:
    name: 1.20.1
    needs: [ meta ]
    if: ${{ contains(github.ref_name, 'main') }}
    secrets: inherit
    uses: ./.github/workflows/publish.yml
    with:
      simulate: ${{ startsWith(github.event.release.name, 'simulate') || github.repository_owner != 'GregTech-Engineering' }}
      branch: 'main'
      tag-name: ${{ github.ref_name }}
      release-body: ${{ github.event.release.body }}
      changelog-body: ${{ needs.meta.outputs.CHANGELOG }}
